// Concept A — « Chaînes » : ~10 niveaux-spec (seeds/provenance fixes).
// Schéma PROVISOIRE : la mission §5 impose de ne le figer qu'après validation des mécaniques.

export const levelsA = [
  {
    id: "a-01",
    title: "Découverte",
    note: "une seule relation à composer",
    tutorial: true,
    line: [3, 2],
    queue: ["+"],
    budget: 1,
    objective: { type: "EXACT_VALUE", value: 5 },
    constraints: [],
    seed: "lab-a-01",
  },
  {
    id: "a-02",
    title: "Priorité",
    note: "l'ordre des transformations décide du résultat",
    line: [6, 6, 2],
    queue: ["+", "*"],
    budget: 2,
    objective: { type: "EXACT_VALUE", value: 24 },
    constraints: [],
    seed: "lab-a-02",
  },
  {
    id: "a-03",
    title: "Division propre",
    note: "÷ exige une divisibilité exacte : planifier",
    line: [48, 4, 6],
    queue: ["/", "/"],
    budget: 2,
    objective: { type: "EXACT_VALUE", value: 2 },
    constraints: [],
    seed: "lab-a-03",
  },
  {
    id: "a-04",
    title: "Préséance inversée",
    note: "× puis + ne donnent pas + puis ×",
    line: [2, 5, 3],
    queue: ["*", "+"],
    budget: 2,
    objective: { type: "EXACT_VALUE", value: 13 },
    constraints: [],
    seed: "lab-a-04",
  },
  {
    id: "a-05",
    title: "Divisibilité réfléchie",
    note: "choisir LA paire divisible, pas n'importe laquelle",
    line: [12, 6, 3],
    queue: ["/", "-"],
    budget: 2,
    objective: { type: "EXACT_VALUE", value: 4 },
    constraints: [],
    seed: "lab-a-05",
  },
  {
    id: "a-06",
    title: "Deux voies équivalentes",
    note: "deux enchaînements distincts atteignent 16",
    line: [8, 4, 2, 6],
    queue: ["+", "*"],
    budget: 2,
    objective: { type: "EXACT_VALUE", value: 16 },
    constraints: [],
    seed: "lab-a-06",
  },
  {
    id: "a-07",
    title: "Cible préservée",
    note: "7 ne doit jamais être fusionnée ; × interdit",
    line: [7, 4, 5, 2],
    queue: ["+", "+"],
    budget: 2,
    objective: { type: "EXACT_VALUE", value: 11 },
    preserve: [7],
    forbid: ["*"],
    constraints: ["preserve", "forbid"],
    seed: "lab-a-07",
  },
  {
    id: "a-08",
    title: "Séquence stricte",
    note: "les opérateurs doivent être consommés dans l'ordre (FIFO)",
    line: [2, 3, 4, 2],
    queue: ["*", "+", "-"],
    budget: 3,
    objective: { type: "EXACT_VALUE", value: 10 },
    sequence: true,
    constraints: ["sequence"],
    seed: "lab-a-08",
  },
  {
    id: "a-09",
    title: "Opérateur exigé",
    note: "il faut avoir utilisé × pour gagner",
    line: [4, 6, 3],
    queue: ["+", "*"],
    budget: 2,
    objective: { type: "EXACT_VALUE", value: 30 },
    require: ["*", "+"],
    constraints: ["require"],
    seed: "lab-a-09",
  },
  {
    id: "a-10",
    title: "Plafond sous tension",
    note: "cap 20 : une fusion trop grande est refusée avant même d'être visible",
    line: [50, 5, 10],
    queue: ["/", "-"],
    budget: 2,
    objective: { type: "EXACT_VALUE", value: 0 },
    cap: 20,
    constraints: ["cap"],
    seed: "lab-a-10",
  },
];

export const levelsA2 = [
  { id: "a2-01", title: "Ouverture", note: "warm-up unique", tutorial: true,
    line: [3, 2], queue: ["+"], budget: 1, objective: { type: "EXACT_VALUE", value: 5 }, constraints: [] },
  { id: "a2-02", title: "Deux voies", note: "m2, deux solutions", tutorial: false,
    line: [2, 3, 5, 4], queue: ["+", "*", "-"], budget: 3, objective: { type: "EXACT_VALUE", value: 11 }, constraints: [] },
  { id: "a2-03", title: "Produit d'abord", note: "chemin unique m2", tutorial: false,
    line: [2, 3, 5, 4], queue: ["+", "*", "-"], budget: 3, objective: { type: "EXACT_VALUE", value: 23 }, constraints: [] },
  { id: "a2-04", title: "Division propre", note: "division exacte", tutorial: false,
    line: [12, 6, 3], queue: ["/", "+"], budget: 2, objective: { type: "EXACT_VALUE", value: 5 }, constraints: [] },
  { id: "a2-05", title: "Multiplicités", note: "4 solutions au min", tutorial: false,
    line: [2, 4, 6, 3], queue: ["+", "*", "-"], budget: 3, objective: { type: "EXACT_VALUE", value: 14 }, constraints: [] },
  { id: "a2-06", title: "Préséance", note: "séquence stricte d'opérateurs", tutorial: false, sequence: true,
    line: [4, 3, 6], queue: ["+", "*"], budget: 2, objective: { type: "EXACT_VALUE", value: 42 }, constraints: [] },
  { id: "a2-07", title: "À l'aveugle", note: "solution profonde m3", tutorial: false,
    line: [2, 7, 1, 4, 3], queue: ["+", "-", "*"], budget: 3, objective: { type: "EXACT_VALUE", value: 42 }, constraints: [] },
  { id: "a2-08", title: "Précision", note: "opérateurs restreints", tutorial: false,
    line: [6, 2, 9, 1, 7], queue: ["+", "-"], budget: 3, objective: { type: "EXACT_VALUE", value: 15 }, constraints: [] },
  { id: "a2-09", title: "Échos", note: "3 solutions m2", tutorial: false,
    line: [5, 3, 8, 1], queue: ["+", "-", "*"], budget: 3, objective: { type: "EXACT_VALUE", value: 28 }, constraints: [] },
  { id: "a2-10", title: "Libre arbitre", note: "4 solutions m2", tutorial: false,
    line: [3, 6, 2, 8], queue: ["+", "-", "*"], budget: 3, objective: { type: "EXACT_VALUE", value: 7 }, constraints: [] },
];