export const LEVELS = [
  {
    id: "b1-1",
    name: "Le Pont",
    scenario: "S1 — immédiat vs préparation",
    rows: 2,
    cols: 3,
    target: 48,
    maxMoves: 2,
    tiles: [
      { kind: "num", v: 12 },
      { kind: "num", v: 4 },
      { kind: "op", v: "*" },
      { kind: "num", v: 3 },
      { kind: "op", v: "+" },
    ],
  },
  {
    id: "b1-2",
    name: "Le 2 partagé",
    scenario: "S7 — ressource partagée exclusive",
    rows: 2,
    cols: 3,
    target: 48,
    maxMoves: 2,
    tiles: [
      { kind: "num", v: 24 },
      { kind: "num", v: 96 },
      { kind: "num", v: 2 },
      { kind: "op", v: "*" },
      { kind: "op", v: "/" },
      { kind: "op", v: "/" },
    ],
  },
  {
    id: "b1-3",
    name: "Quatre routes",
    scenario: "S8 — le coup ne suffit pas, l'état d'après décide",
    rows: 3,
    cols: 4,
    target: 48,
    maxMoves: 2,
    tiles: [
      { kind: "num", v: 24 },
      { kind: "num", v: 2 },
      { kind: "num", v: 50 },
      { kind: "num", v: 12 },
      { kind: "op", v: "*" },
      { kind: "num", v: 4 },
      { kind: "op", v: "-" },
      { kind: "num", v: 96 },
      { kind: "op", v: "/" },
      { kind: "num", v: 3 },
    ],
  },
  {
    id: "b1-4",
    name: "La Falaise",
    scenario: "S4/S9 — piège : un premier coup mène au cul-de-sac (bloqué ≠ échec)",
    rows: 1,
    cols: 5,
    target: 35,
    maxMoves: 2,
    tiles: [
      { kind: "num", v: 5 },
      { kind: "num", v: 7 },
      { kind: "op", v: "*" },
      { kind: "op", v: "+" },
    ],
  },
  {
    id: "b1-5",
    name: "Division exacte",
    scenario: "K-0 + C-3 — rejets non destructifs, ancrage sur l'opérande A",
    rows: 2,
    cols: 4,
    target: 48,
    maxMoves: 2,
    tiles: [
      { kind: "num", v: 50 },
      { kind: "num", v: 4 },
      { kind: "num", v: 12 },
      { kind: "op", v: "/" },
      { kind: "op", v: "-" },
      { kind: "op", v: "*" },
    ],
  },
  {
    id: "b1-6",
    name: "La Chaîne",
    scenario: "B1-B — préparation obligatoire (aucune solution en 1 coup)",
    rows: 1,
    cols: 8,
    target: 48,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 3 },
      { kind: "num", v: 2 },
      { kind: "num", v: 4 },
      { kind: "num", v: 8 },
      { kind: "op", v: "*" },
      { kind: "op", v: "+" },
    ],
  },
];

export function levelBy(n) {
  return LEVELS.find((l) => l.id === n) ?? null;
}