export const LEVELS = [
  {
    id: "b1-1",
    name: "Le Pont",
    scenario: "S1 — immédiat vs préparation",
    rows: 2,
    cols: 3,
    target: 48,
    maxMoves: 2,
    tiles: [
      { kind: "num", v: 12 },
      { kind: "num", v: 4 },
      { kind: "op", v: "*" },
      { kind: "num", v: 3 },
      { kind: "op", v: "+" },
    ],
  },
  {
    id: "b1-2",
    name: "Le 2 partagé",
    scenario: "S7 — ressource partagée exclusive",
    rows: 2,
    cols: 3,
    target: 48,
    maxMoves: 2,
    tiles: [
      { kind: "num", v: 24 },
      { kind: "num", v: 96 },
      { kind: "num", v: 2 },
      { kind: "op", v: "*" },
      { kind: "op", v: "/" },
      { kind: "op", v: "/" },
    ],
  },
  {
    id: "b1-3",
    name: "Quatre routes",
    scenario: "S8 — le coup ne suffit pas, l'état d'après décide",
    rows: 3,
    cols: 4,
    target: 48,
    maxMoves: 2,
    tiles: [
      { kind: "num", v: 24 },
      { kind: "num", v: 2 },
      { kind: "num", v: 50 },
      { kind: "num", v: 12 },
      { kind: "op", v: "*" },
      { kind: "num", v: 4 },
      { kind: "op", v: "-" },
      { kind: "num", v: 96 },
      { kind: "op", v: "/" },
      { kind: "num", v: 3 },
    ],
  },
  {
    id: "b1-4",
    name: "La Falaise",
    scenario: "S4/S9 — piège : un premier coup mène au cul-de-sac (bloqué ≠ échec)",
    rows: 1,
    cols: 5,
    target: 35,
    maxMoves: 2,
    tiles: [
      { kind: "num", v: 5 },
      { kind: "num", v: 7 },
      { kind: "op", v: "*" },
      { kind: "op", v: "+" },
    ],
  },
  {
    id: "b1-5",
    name: "Division exacte",
    scenario: "K-0 + C-3 — rejets non destructifs, ancrage sur l'opérande A",
    rows: 2,
    cols: 4,
    target: 48,
    maxMoves: 2,
    tiles: [
      { kind: "num", v: 50 },
      { kind: "num", v: 4 },
      { kind: "num", v: 12 },
      { kind: "op", v: "/" },
      { kind: "op", v: "-" },
      { kind: "op", v: "*" },
    ],
  },
  {
    id: "b1-6",
    name: "La Chaîne",
    scenario: "B1-B — préparation obligatoire (aucune solution en 1 coup)",
    rows: 1,
    cols: 8,
    target: 48,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 3 },
      { kind: "num", v: 2 },
      { kind: "num", v: 4 },
      { kind: "num", v: 8 },
      { kind: "op", v: "*" },
      { kind: "op", v: "+" },
    ],
  },
];

export function levelBy(n) {
  return LEVELS.find((l) => l.id === n) ?? null;
}

export const LADDER = [
  {
    id: "N1",
    world: "W1",
    name: "La Première Formule",
    idea: "une idée : sélection → preview → transformation (geste unique)",
    hud: ["target", "moves"],
    rows: 1,
    cols: 3,
    target: 5,
    maxMoves: 1,
    tiles: [
      { kind: "num", v: 2 },
      { kind: "op", v: "+" },
      { kind: "num", v: 3 },
    ],
  },
  {
    id: "N2",
    world: "W1",
    name: "Deux Chemins",
    idea: "plusieurs formules vers le même objectif (choix = valeur)",
    hud: ["target", "moves", "score"],
    rows: 1,
    cols: 5,
    target: 5,
    maxMoves: 1,
    tiles: [
      { kind: "num", v: 2 },
      { kind: "num", v: 3 },
      { kind: "op", v: "+" },
      { kind: "num", v: 4 },
      { kind: "num", v: 1 },
    ],
  },
  {
    id: "N3",
    world: "W1",
    name: "L'État Après",
    idea: "même objectif, états post-coup différents (l'état d'après compte)",
    hud: ["target", "moves", "score"],
    rows: 1,
    cols: 5,
    target: 24,
    maxMoves: 1,
    tiles: [
      { kind: "num", v: 6 },
      { kind: "num", v: 4 },
      { kind: "op", v: "*" },
      { kind: "num", v: 8 },
      { kind: "num", v: 3 },
    ],
  },
  {
    id: "N4",
    world: "W2",
    name: "Le Sacrifice",
    idea: "premier coup peu rentable, utile ensuite (préparation)",
    hud: ["target", "moves", "score"],
    rows: 1,
    cols: 5,
    target: 40,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 12 },
      { kind: "num", v: 3 },
      { kind: "op", v: "*" },
      { kind: "num", v: 4 },
      { kind: "op", v: "+" },
    ],
  },
  {
    id: "N5",
    world: "W3",
    name: "La Chaîne",
    idea: "résultat réutilisé → chaîne (aucune solution en 1 coup)",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 6,
    target: 48,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 3 },
      { kind: "num", v: 2 },
      { kind: "op", v: "+" },
      { kind: "num", v: 4 },
      { kind: "op", v: "*" },
      { kind: "num", v: 8 },
    ],
  },
  {
    id: "N6",
    world: "W5",
    name: "L'Optimisation",
    idea: "solution rapide vs solution préparée (le score devient décision)",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 5,
    target: 48,
    maxMoves: 2,
    tiles: [
      { kind: "num", v: 12 },
      { kind: "num", v: 4 },
      { kind: "op", v: "*" },
      { kind: "num", v: 3 },
      { kind: "op", v: "+" },
    ],
  },
  {
    id: "N7",
    world: "W2",
    name: "Le Choix Précoce",
    idea: "deux natures de préparation (quel couple multiplier d'abord)",
    hud: ["target", "moves", "score"],
    rows: 1,
    cols: 7,
    target: 30,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 3 },
      { kind: "num", v: 2 },
      { kind: "num", v: 24 },
      { kind: "num", v: 18 },
      { kind: "op", v: "*" },
      { kind: "op", v: "+" },
      { kind: "op", v: "-" },
    ],
  },
  {
    id: "N8",
    world: "W3",
    name: "Double Chaîne",
    idea: "deux chaînes différentes vers le même objectif",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 6,
    target: 24,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 2 },
      { kind: "num", v: 14 },
      { kind: "num", v: 7 },
      { kind: "num", v: 5 },
      { kind: "op", v: "+" },
      { kind: "op", v: "*" },
    ],
  },
  {
    id: "N9",
    world: "W4",
    name: "La Division Prépare",
    idea: "diviser d'abord, ajouter ensuite (chaîne par réutilisation)",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 7,
    target: 24,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 16 },
      { kind: "num", v: 20 },
      { kind: "num", v: 2 },
      { kind: "num", v: 14 },
      { kind: "op", v: "/" },
      { kind: "op", v: "*" },
      { kind: "op", v: "+" },
    ],
  },
  {
    id: "N10",
    world: "W5",
    name: "Pas de Marge",
    idea: "le budget est exact : les deux coups sont obligatoires",
    hud: ["target", "moves", "score"],
    rows: 1,
    cols: 7,
    target: 36,
    maxMoves: 2,
    tiles: [
      { kind: "num", v: 8 },
      { kind: "num", v: 12 },
      { kind: "num", v: 9 },
      { kind: "num", v: 6 },
      { kind: "op", v: "*" },
      { kind: "op", v: "+" },
      { kind: "op", v: "-" },
    ],
  },
  {
    id: "N11",
    world: "W5",
    name: "Les Détours Payants",
    idea: "le détour chaîné vaut plus que la victoire directe",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 7,
    target: 60,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 12 },
      { kind: "num", v: 5 },
      { kind: "num", v: 3 },
      { kind: "num", v: 16 },
      { kind: "op", v: "*" },
      { kind: "op", v: "+" },
      { kind: "op", v: "-" },
    ],
  },
  {
    id: "N12",
    world: "W2",
    name: "Le Détour Sacrifié",
    idea: "victoire immédiate sans chaîne vs route construite",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 7,
    target: 30,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 24 },
      { kind: "num", v: 4 },
      { kind: "num", v: 3 },
      { kind: "num", v: 6 },
      { kind: "op", v: "+" },
      { kind: "op", v: "*" },
      { kind: "op", v: "-" },
    ],
  },
  {
    id: "N13",
    world: "W3",
    name: "Le Long Courrier",
    idea: "trois coups prévus, chaque étape réutilisée",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 8,
    target: 84,
    maxMoves: 4,
    tiles: [
      { kind: "num", v: 2 },
      { kind: "num", v: 8 },
      { kind: "num", v: 6 },
      { kind: "num", v: 10 },
      { kind: "num", v: 18 },
      { kind: "op", v: "+" },
      { kind: "op", v: "*" },
      { kind: "op", v: "-" },
    ],
  },
  {
    id: "N14",
    world: "W4",
    name: "Le Partage Obligé",
    idea: "÷ nécessaire : l'ordre des opérations change le score",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 7,
    target: 60,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 4 },
      { kind: "num", v: 14 },
      { kind: "num", v: 20 },
      { kind: "num", v: 5 },
      { kind: "op", v: "/" },
      { kind: "op", v: "+" },
      { kind: "op", v: "*" },
    ],
  },
  {
    id: "N15",
    world: "W6",
    name: "Le Détective",
    idea: "une seule formule possible, à déduire",
    hud: ["target", "moves", "score"],
    rows: 1,
    cols: 8,
    target: 10,
    maxMoves: 1,
    tiles: [
      { kind: "num", v: 6 },
      { kind: "num", v: 16 },
      { kind: "num", v: 18 },
      { kind: "num", v: 10 },
      { kind: "op", v: "*" },
      { kind: "op", v: "+" },
      { kind: "op", v: "-" },
      { kind: "op", v: "/" },
    ],
  },
  {
    id: "N16",
    world: "W6",
    name: "La Synthèse",
    idea: "capstone : × puis ÷, multiples routes, scores étagés",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 9,
    target: 72,
    maxMoves: 4,
    tiles: [
      { kind: "num", v: 24 },
      { kind: "num", v: 9 },
      { kind: "num", v: 4 },
      { kind: "num", v: 5 },
      { kind: "num", v: 15 },
      { kind: "op", v: "+" },
      { kind: "op", v: "*" },
      { kind: "op", v: "-" },
      { kind: "op", v: "/" },
    ],
  },
  {
    id: "N17",
    world: "W1",
    name: "Les Quatre Chemins",
    idea: "quatre formules différentes mènent au même but : choisir la meilleure",
    hud: ["target", "moves", "score"],
    rows: 1,
    cols: 6,
    target: 18,
    maxMoves: 1,
    tiles: [
      { kind: "num", v: 14 },
      { kind: "num", v: 2 },
      { kind: "num", v: 9 },
      { kind: "num", v: 4 },
      { kind: "op", v: "+" },
      { kind: "op", v: "*" },
    ],
  },
  {
    id: "N18",
    world: "W1",
    name: "Préparer puis Toucher",
    idea: "construire d'abord (3×8=24), puis viser : 24+24 fait le but",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 6,
    target: 48,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 3 },
      { kind: "num", v: 8 },
      { kind: "num", v: 18 },
      { kind: "num", v: 24 },
      { kind: "op", v: "+" },
      { kind: "op", v: "*" },
    ],
  },
  {
    id: "N19",
    world: "W2",
    name: "Le Coup Sacrifié",
    idea: "un coup qui ne rapporte rien (2+1=3) puis 3×8 touche le but",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 6,
    target: 24,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 2 },
      { kind: "num", v: 1 },
      { kind: "num", v: 7 },
      { kind: "num", v: 8 },
      { kind: "op", v: "+" },
      { kind: "op", v: "*" },
    ],
  },
  {
    id: "N20",
    world: "W2",
    name: "La Double Préparation",
    idea: "préparer deux coups (10−8=2, puis 2×2=4) avant de toucher 36",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 7,
    target: 40,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 8 },
      { kind: "num", v: 2 },
      { kind: "num", v: 36 },
      { kind: "num", v: 10 },
      { kind: "op", v: "+" },
      { kind: "op", v: "*" },
      { kind: "op", v: "-" },
    ],
  },
  {
    id: "N21",
    world: "W2",
    name: "Les Préparations Rivales",
    idea: "deux façons de préparer, deux scores : à toi de trancher",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 7,
    target: 48,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 8 },
      { kind: "num", v: 10 },
      { kind: "num", v: 9 },
      { kind: "num", v: 4 },
      { kind: "num", v: 3 },
      { kind: "op", v: "+" },
      { kind: "op", v: "*" },
    ],
  },
  {
    id: "N22",
    world: "W3",
    name: "La Chaîne à Deux Voies",
    idea: "deux chaînes possibles construisent le but, chacune réutilise son résultat",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 7,
    target: 60,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 20 },
      { kind: "num", v: 6 },
      { kind: "num", v: 30 },
      { kind: "num", v: 15 },
      { kind: "op", v: "+" },
      { kind: "op", v: "*" },
      { kind: "op", v: "-" },
    ],
  },
  {
    id: "N23",
    world: "W3",
    name: "La Fuite en Avant",
    idea: "une seule route : chaque étape construit la suivante jusqu'au but",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 8,
    target: 72,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 16 },
      { kind: "num", v: 9 },
      { kind: "num", v: 1 },
      { kind: "num", v: 18 },
      { kind: "num", v: 14 },
      { kind: "op", v: "+" },
      { kind: "op", v: "*" },
      { kind: "op", v: "-" },
    ],
  },
  {
    id: "N24",
    world: "W3",
    name: "La Chaîne Longue",
    idea: "beaucoup de chaînes possibles : explore et compare les scores",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 8,
    target: 48,
    maxMoves: 4,
    tiles: [
      { kind: "num", v: 20 },
      { kind: "num", v: 2 },
      { kind: "num", v: 15 },
      { kind: "num", v: 3 },
      { kind: "num", v: 7 },
      { kind: "op", v: "+" },
      { kind: "op", v: "*" },
      { kind: "op", v: "-" },
    ],
  },
  {
    id: "N25",
    world: "W4",
    name: "Le Partage",
    idea: "le partage réduit 36 : 36÷2=18, puis 18+18 atteint le but",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 7,
    target: 36,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 36 },
      { kind: "num", v: 8 },
      { kind: "num", v: 2 },
      { kind: "num", v: 18 },
      { kind: "op", v: "/" },
      { kind: "op", v: "/" },
      { kind: "op", v: "+" },
    ],
  },
  {
    id: "N26",
    world: "W4",
    name: "L'Entrée Obligée",
    idea: "tout doit commencer par un partage : 14÷7=2 ouvre la route",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 7,
    target: 36,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 14 },
      { kind: "num", v: 7 },
      { kind: "num", v: 6 },
      { kind: "num", v: 12 },
      { kind: "op", v: "/" },
      { kind: "op", v: "/" },
      { kind: "op", v: "*" },
    ],
  },
  {
    id: "N27",
    world: "W4",
    name: "Diviser pour Grandir",
    idea: "16÷8=2 réduit puis 2×30 atteint le but : le partage prépare le grandir",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 7,
    target: 60,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 8 },
      { kind: "num", v: 16 },
      { kind: "num", v: 3 },
      { kind: "num", v: 30 },
      { kind: "op", v: "/" },
      { kind: "op", v: "*" },
      { kind: "op", v: "*" },
    ],
  },
  {
    id: "N28",
    world: "W5",
    name: "Trois Portes",
    idea: "trois routes gagnantes, trois scores : jamais le même chemin",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 8,
    target: 84,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 6 },
      { kind: "num", v: 16 },
      { kind: "num", v: 36 },
      { kind: "num", v: 2 },
      { kind: "num", v: 18 },
      { kind: "op", v: "+" },
      { kind: "op", v: "*" },
      { kind: "op", v: "-" },
    ],
  },
  {
    id: "N29",
    world: "W5",
    name: "Le Budget Juste",
    idea: "tous les coups comptent : chaque coup doit préparer ou toucher",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 8,
    target: 48,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 8 },
      { kind: "num", v: 18 },
      { kind: "num", v: 4 },
      { kind: "num", v: 3 },
      { kind: "num", v: 7 },
      { kind: "op", v: "+" },
      { kind: "op", v: "*" },
      { kind: "op", v: "-" },
    ],
  },
  {
    id: "N30",
    world: "W5",
    name: "Le Choix du Score",
    idea: "viser vite (8×15) ou préparer d'abord : le score répond du choix",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 8,
    target: 120,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 24 },
      { kind: "num", v: 8 },
      { kind: "num", v: 9 },
      { kind: "num", v: 1 },
      { kind: "num", v: 15 },
      { kind: "op", v: "*" },
      { kind: "op", v: "+" },
      { kind: "op", v: "-" },
    ],
  },
  {
    id: "N31",
    world: "W6",
    name: "La Tour",
    idea: "chaîne de trois résultats : diviser, additionner, multiplier en cascade",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 9,
    target: 168,
    maxMoves: 4,
    tiles: [
      { kind: "num", v: 15 },
      { kind: "num", v: 2 },
      { kind: "num", v: 1 },
      { kind: "num", v: 12 },
      { kind: "num", v: 36 },
      { kind: "op", v: "/" },
      { kind: "op", v: "*" },
      { kind: "op", v: "+" },
      { kind: "op", v: "-" },
    ],
  },
  {
    id: "N32",
    world: "W6",
    name: "Le Puzzle Étendu",
    idea: "partager pour ajuster, puis multiplier : six routes, belle variété",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 8,
    target: 120,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 24 },
      { kind: "num", v: 30 },
      { kind: "num", v: 18 },
      { kind: "num", v: 2 },
      { kind: "num", v: 6 },
      { kind: "op", v: "/" },
      { kind: "op", v: "*" },
      { kind: "op", v: "+" },
    ],
  },
  {
    id: "N33",
    world: "W6",
    name: "Le Détective Confirmé",
    idea: "une seule route sur trois coups : déduire, ne pas essayer",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 8,
    target: 96,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 15 },
      { kind: "num", v: 2 },
      { kind: "num", v: 14 },
      { kind: "num", v: 36 },
      { kind: "num", v: 5 },
      { kind: "op", v: "+" },
      { kind: "op", v: "*" },
      { kind: "op", v: "-" },
    ],
  },
  {
    id: "N34",
    world: "W6",
    name: "La Synthèse II",
    idea: "quatre opérations, des chains profondes, beaucoup de fins possibles",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 9,
    target: 144,
    maxMoves: 4,
    tiles: [
      { kind: "num", v: 8 },
      { kind: "num", v: 15 },
      { kind: "num", v: 1 },
      { kind: "num", v: 16 },
      { kind: "num", v: 2 },
      { kind: "op", v: "/" },
      { kind: "op", v: "*" },
      { kind: "op", v: "+" },
      { kind: "op", v: "-" },
    ],
  },
  {
    id: "N35",
    world: "W6",
    name: "La Convergence",
    idea: "toutes les voies chaînées convergent vers le but, chacune son score",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 9,
    target: 168,
    maxMoves: 3,
    tiles: [
      { kind: "num", v: 18 },
      { kind: "num", v: 8 },
      { kind: "num", v: 30 },
      { kind: "num", v: 16 },
      { kind: "num", v: 5 },
      { kind: "op", v: "+" },
      { kind: "op", v: "*" },
      { kind: "op", v: "-" },
      { kind: "op", v: "/" },
    ],
  },
  {
    id: "N36",
    world: "W6",
    name: "Le Maître",
    idea: "le couronnement : six nombres, quatre opérations, des stratégies à l'infini",
    hud: ["target", "moves", "score", "chain"],
    rows: 1,
    cols: 10,
    target: 360,
    maxMoves: 4,
    tiles: [
      { kind: "num", v: 18 },
      { kind: "num", v: 24 },
      { kind: "num", v: 6 },
      { kind: "num", v: 2 },
      { kind: "num", v: 3 },
      { kind: "num", v: 10 },
      { kind: "op", v: "+" },
      { kind: "op", v: "*" },
      { kind: "op", v: "-" },
      { kind: "op", v: "/" },
    ],
  },
];

export function ladderBy(n) {
  return LADDER.find((l) => l.id === n) ?? null;
}

export const WORLDS = [
  { id: "W1", name: "La Formule", concept: "formule, transformation, objectif", kind: "onboarding" },
  { id: "W2", name: "La Préparation", concept: "préparer avant de gagner, coup non rentable qui sert ensuite", kind: "prep" },
  { id: "W3", name: "La Chaîne", concept: "réutilisation du résultat ancré, profondeur de chaîne", kind: "chain" },
  { id: "W4", name: "La Division", concept: "÷ outil (prépare, réduit) puis ÷ contrainte (nécessaire)", kind: "div" },
  { id: "W5", name: "Le Budget", concept: "coups comptés, arbitrage rapide / préparé / stratégique", kind: "budget" },
  { id: "W6", name: "La Synthèse", concept: "combinaison des outils, déduction, capstone", kind: "synth" },
];

export function worldOf(id) {
  return ladderBy(id)?.world ?? null;
}

export function levelsInWorld(worldId) {
  return LADDER.filter((l) => l.world === worldId);
}

export function nextLevel(id) {
  const i = LADDER.findIndex((l) => l.id === id);
  return i >= 0 && i < LADDER.length - 1 ? LADDER[i + 1] : null;
}

export function prevLevel(id) {
  const i = LADDER.findIndex((l) => l.id === id);
  return i > 0 ? LADDER[i - 1] : null;
}

export function firstLevelOf(worldId) {
  const w = levelsInWorld(worldId);
  return w.length ? w[0] : null;
}

export function lastLevelOf(worldId) {
  const w = levelsInWorld(worldId);
  return w.length ? w[w.length - 1] : null;
}